# Generated by Django 6.0.7 on 2026-08-01 12:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('sinopse', models.TextField(max_length=1000)),
                ('ano_lancamento', models.IntegerField()),
                ('duracao_minutos', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='capas_filmes/')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('nota', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('comentario', models.TextField(max_length=1000)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='FilmesApp.filme')),
            ],
        ),
        migrations.AddField(
            model_name='filme',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FilmesApp.genero'),
        ),
    ]
