# Generated by Django 6.0.7 on 2026-08-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='trailer',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
